config/routes.rb
Rails.application.routes.draw do
  post 'parse', to: 'anystyle#parse', as: :parse
  post 'format', to: 'anystyle#format', as: :format

  root 'anystyle#index'
end

app/models/account.rb
class Account < ApplicationRecord
  before_create :generate_access_token

  validates :access_token,
    presence: true,
    uniqueness: true,
    length: { minimum: 32, maximum: 256 },
    unless: :new_record?

  validates :user,
    presence: true,
    uniqueness: true,
    format: {
      with: /\A[^@\s]+@[^@\s]+\Z/i,
      on: :create
    }

  class << self
    def verify(access_token)
      account = find_by_access_token! access_token
    ensure
      account&.increment! :access_count
    end
  end

  def generate_access_token
    begin
      write_attribute :access_token, SecureRandom.hex(16)
    end while Account.exists?(access_token: access_token)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sequence.rb
class Sequence < ApplicationRecord
  validates :xml, presence: true, uniqueness: true
end

app/controllers/anystyle_controller.rb
class AnystyleController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :parse
  before_action :verify_access_token, only: :parse

  rescue_from ActionController::ParameterMissing, with: :bad_request

  def index
  end

  def parse
    input = params.require(:input)

    if input.length <= Rails.configuration.anystyle.parse_limit
      render_dataset parser.parse(input, format: 'wapiti')
    else
      bad_request 'status.excessive'
    end
  ensure
    response.headers['X-AnyStyle-Last-Modified'] = model_time
  end

  def format
    input = JSON.parse(params.require(:dataset))
    sequences = []

    dataset = Wapiti::Dataset.new(input.map { |s|
      seq = Wapiti::Sequence.new(s['tokens'].map { |t|
        Wapiti::Token.new t['value'], label: t['label']
      })

      sequences << Sequence.new(xml: seq.to_xml) if s['pertinent']

      seq
    })

    render_dataset dataset
  ensure
    save_training_data sequences if train_model?
  end

  private

  def render_dataset(dataset)
    respond_to do |format|
      format.json {
        render json: dataset.map { |s| s.map { |t| [t.label, t.value] } }
      }
      format.csl {
        render json: parser.format_csl(dataset, date_format: 'citeproc')
      }
      format.bibtex {
        send_data parser.format_bibtex(dataset),
          filename: 'anystyle.bib',
          type: :bibtex
      }
      format.xml {
        render xml: dataset.to_xml
      }
    end
  end

  def parser
    AnyStyle.parser
  ensure
    AnyStyle.parser.reload if AnyStyle.parser.stale?
  end

  def train_model?
    !!params[:reviewed]
  end

  def save_training_data(sequences)
    saved_count = sequences.map(&:save).count(true)

    unless saved_count.zero? || TrainModelJob.pending?
      TrainModelJob.perform_later(parser.model.path)
    end
  end

  def model_time
    view_context.time_ago_in_words parser.mtime, include_seconds: true
  end

  def verify_access_token
    verify_authenticity_or_access_token
  rescue
    not_authorized
  end

  def verify_authenticity_or_access_token
    if params.key? :access_token
      Account.verify params.require(:access_token)
    else
      verify_authenticity_token
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def bad_request(message = 'status.bad_request')
    render status: :bad_request, plain: I18n.t(message)
  end

  def not_authorized(message = 'status.unauthorized')
    render status: :unauthorized, plain: I18n.t(message)
  end
end

app/helpers/anystyle_helper.rb
module AnystyleHelper
  def doc_url
    Rails.configuration.anystyle[:doc]
  end

  def gem_url
    Rails.configuration.anystyle[:gem]
  end

  def git_url(*args)
    [Rails.configuration.anystyle[:git], *args].compact.join('/')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def angular_template(id, options = { partial: id })
    content_tag :script, id: id, type: 'text/ng-template' do
      render options
    end
  end
end

app/views/anystyle/_documentation.html.haml
%section.documentation
  %section#ui
    .container
      .row
        .col-md-12
          %h1=t "documentation.title"
      .row
        .col-md-12
          %h2=t "documentation.web.title"
      .row
        .col-md-4.hyphenate=t "documentation.web.left_html"
        .col-md-4.hyphenate=t "documentation.web.center_html",
          core_url: git_url("blob/master/res/parser/core.xml")
        .col-md-4.hyphenate=t "documentation.web.right_html"
  %section#rubygem
    .container
      .row
        .col-md-12
          %h2=t "documentation.ruby.title"
          %p.lead=t "documentation.ruby.install"
          %pre
            %code
              :preserve
                $ [sudo] gem install anystyle
          %p=t "documentation.ruby.usage"
          %pre
            %code
              :preserve
                >> require "anystyle"

                >> AnyStyle.parse """
                    Turing, Alan, Computing Machinery and Intelligence, Mind 59, pp 433-460 (1950)
                   """
                => [{
                     :type => "article-journal",
                     :author => [{ :family => "Turing", :given => "Alan" }],
                     :date => ["1950"],
                     :title => ["Computing Machinery and Intelligence"],
                     :"container-title" => ["Mind"],
                     :volume => ["59"],
                     :pages => ["433–460"],
                     :language => "en",
                     :scripts => ["Common", "Latin"]
                   }]

          %p=t "documentation.ruby.more_html", doc_url: doc_url
  %section#cli
    .container
      .row
        .col-md-12
          %h2=t "documentation.cli.title"
          %p.lead=t "documentation.cli.install"
          %pre
            %code
              :preserve
                $ [sudo] gem install anystyle-cli
          %p=t "documentation.ruby.usage"
          %pre
            %code
              :preserve
                $ anystyle --help

                NAME
                    anystyle - Finds and parses bibliographic references

                SYNOPSIS
                    anystyle [global options] command [command options] [arguments...]

                VERSION
                    1.3.3 (cli 1.2.0, data 1.2.0)

                GLOBAL OPTIONS
                    -F, --finder-model=file - Set the finder model file (default: none)
                    -P, --parser-model=file - Set the parser model file (default: none)
                    --adapter=name          - Set the dictionary adapter (default: ruby)
                    -f, --format=name       - Set the output format (default: ["json"])
                    --pdfinfo=path          - Set the path for pdfinfo (default: none)
                    --pdftotext=path        - Set the path for pdftotext (default: none)
                    --help                  - Show this message
                    --[no-]stdout           - Print results directly to stdout
                    --[no-]verbose          - Print status messages to stderr
                    --version               - Display the program version
                    -w, --[no-]overwrite    - Allow overwriting existing files

                COMMANDS
                    check   - Check tagged documents or references
                    find    - Find and extract references from text documents
                    help    - Shows a list of commands or help for one command
                    license - Print license information
                    parse   - Parse and convert references
                    train   - Create a new finder or parser model

app/views/anystyle/_footer.html.haml
%footer
  .container
    .row
      .col-md-12
        %h1=t "footer.title"
        %p.lead=t "footer.lead_html"
        .row
          .col-md-6.hyphenate
            %p=t "footer.left_html"
            %p.lead.text-center
              =link_to git_url("issues") do
                %i.glyphicon.glyphicon-circle-arrow-right><
                %span=t "footer.issue"
          .col-md-6.hyphenate
            %p=t "footer.right_html"
            %p.lead.text-center
              =mail_to "sylvester@keil.or.at", encode: 'javascript' do
                %i.glyphicon.glyphicon-circle-arrow-right><
                %span=t "footer.contact"
        %p.credits
          Developed by #{link_to "Sylvester Keil", "https://github.com/inukshuk"}.
          Designed by #{link_to "Flachware", "http://flachware.com"}.
          With #{fa_icon "heart-broken", title: "a broken heart"} at aliceblue.
        %ul.list-unstyled.footer-links.text-center
          %li><= 'v' << AnyStyle::VERSION
          %li><= link_to "GitHub", git_url
          %li><= link_to "Issues", git_url("issues")
          %li><= link_to "RubyDoc", doc_url
          %li><= link_to "RubyGem", gem_url
        %p.logos
          %a.flachware(href="http://flachware.com")><
          %span.aliceblue><

app/views/anystyle/_pagination.html.haml
%ul.pagination.pagination-lg(ng-show="totalPages > 1")
  %li(ng-repeat="page in pages track by $index" ng-class="{active: page.active, disabled: page.disabled}")
    %a(href="" ng-click="selectPage(page.number)") {{page.text}}

app/views/anystyle/_parser.html.haml
%section.anystyle-parser
  %section#source
    .container
      .row
        .col-md-10.col-md-offset-1.col-lg-8.col-lg-offset-2

          %h2.text-center
            %em= t "parser.source.title"
          .alert.alert-danger.alert-dismissable(ng-if="error")
            %button.close(ng-click="error = false" type="button" aria-hidden="true") &times;
            %strong= t("parser.error.heading")
            =t 'parser.error.message'

          .alert.alert-warning(ng-if="excessive")
            %strong= t("parser.excessive.heading")
            =t 'parser.excessive.message', limit: 1000

          %form
            .form-group(role="form" spinner="output.processing")
              %textarea.form-control{ "ng-model" => "source",
                placeholder: t("parser.source.placeholder"),
                rows: "10",
                spellcheck: "false",
                "ng-disabled" => "output && !output.$resolved",
                "ng-class" => "{ pristine: !source }" }

            %button.btn.btn-primary.btn-lg.btn-block{ "ng-click" => "parse()",
              "ng-disabled" => "!source || (output && !output.$resolved) || excessive" }
              =t 'parser.source.submit'
              %ng-pluralize{ count: 'input.lines.length',
                when: "{ '0': '', 'one': 'one reference', 'other': '{} references' }" }

  %section#editor(ng-class="{ disabled: !output.$resolved }")
    .step-arrow
      %span.glyphicon.glyphicon-arrow-down

    .container
      .row
        .col-md-12
          %h2.text-center
            %em= t "parser.editor.title"
      .row.affix-container
        .col-md-8
          %ul#tokens.list-unstyled
            %li.clearfix(ng-repeat="reference in output | startFrom: offset | limitTo: ipp")
              %span.label{ "ng-repeat" => "token in reference.tokens",
                "class" => "label-{{token.label}}",
                "ng-class" => "{ marked: token.marked, 'last-of-label': $last || token.label !== reference.tokens[$index + 1].label}",
                "ng-dblclick" => "pick(reference, token, $event)",
                "ng-mousedown" => "mark(reference, token, $event)" } {{token.value}}

        .col-md-4(style="position: static")
          .sidebar(affix offset-top="30" offset-bottom="30")
            %button.btn.btn-lg.btn-primary.btn-block(ng-mousedown="open()" ng-disabled="!anchor")
              = t 'parser.editor.tag'
            %ul.list-unstyled
              %li(ng-repeat="label in history.labels")
                %button.btn.btn-success.btn-block(ng-mousedown="tag(label)" ng-disabled="!anchor" class="label-{{label.name}}") {{label.translation}}

      .row
        .col-md-12.text-center
          %nav
            %ul(pagination total-items="output.length" page="page" items-per-page="ipp" max-size="5")

          %time.timestamp
            Model last updated {{output.mtime}} ago

  %section#export(ng-class="{ disabled: !output.$resolved }")
    .step-arrow.text-center
      %span.glyphicon.glyphicon-arrow-down

    .container
      .row
        .col-md-12
          %h2.text-center
            %em= t "parser.save.title"

          =form_tag format_path, method: 'post', target: '_blank', class: 'form-inline' do
            =hidden_field_tag 'dataset'
            =hidden_field_tag 'format'
            .lead
              .form-group
                .checkbox
                  %label(ng-class="{ disabled: !output.edited }")
                    %input(type="checkbox" name="reviewed" ng-model="output.reviewed" ng-disabled="!output.edited")
                    =t "parser.save.train"

            .text-center
              %button.btn.btn-success.btn-lg(ng-click="save('csl')" ng-disabled="!output.$resolved") CSL-JSON
              %button.btn.btn-success.btn-lg(ng-click="save('bibtex')" ng-disabled="!output.$resolved") BibTeX
              // %button.btn.btn-success.btn-lg(ng-click="save('json')" ng-disabled="!output.$resolved") JSON
              %button.btn.btn-success.btn-lg(ng-click="save('xml')" ng-disabled="!output.$resolved") XML

  .label-selector(ng-show="selector" ng-mousedown="close()")
    .modal-backdrop.fade(ng-class="{ in: selector }")
    .container.fade(ng-class="{ in: selector }")
      .row
        - AnyStyle.labels.each do |label, translation|
          .col-md-4
            %button.btn.btn-lg.btn-success.btn-block(ng-mousedown="tag({ name: '#{label}', translation: '#{translation}' })" class="label-#{label}")= translation

app/views/anystyle/index.html.haml
%header
  .jumbotron
    .container
      %span.logo
        %span.transform
          %span Any
          %span> Style
      %h1= t "index.claim_html"
      %a.btn.btn-default.btn-lg(href=git_url)
        = fa_icon "star", text: t("index.github")
      %a.btn.btn-default.btn-lg(href=gem_url)>
        %i.ruby-icon
        =t "index.gem"

%section#main(anystyle-parser)

= render partial: "documentation"
= render partial: "footer"

app/views/layouts/application.html.haml
!!!
%html(lang="en")
  %head
    %title= t "title"

    %meta{name: "description", content: t("description") }
    %meta{name: "keywords", content: t("keywords") }

    = stylesheet_link_tag "application", media: "all"

    = csrf_meta_tags
    = csp_meta_tag

  %body(ng-app="anystyle")
    = yield

    = angular_template 'anystyle/parser'
    = angular_template '/template/pagination/pagination.html', partial: 'anystyle/pagination'

    = javascript_include_tag "application", async: true